"use client";

const Testimonals = [
  {
    id: 1,
    image: "/Assets/Images/Profile-img-1.png",
    title: "Exceptional Service!",
    desc: "Our experience with Estatein was outstanding. Their team's dedication and professionalism made finding our dream home a breeze. Highly recommended!",
    rating: [
      { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
      { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
      { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
      { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
      { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
    ],
    name: "Wade Warren",
    country: "USA, California",
  },
  {
    id: 2,
    image: "/Assets/Images/Profile-img- 2.png",
    title: "Efficient and Reliable",
    desc: "Estatein provided us with top-notch service. They helped us sell our property quickly and at a great price. We couldn't be happier with the results.",
    rating: [
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
    ],
    name: "Emelie Thomson",
    country: "USA, Florida",
  },
  {
    id: 3,
    image: "/Assets/Images/Profile-img-3.png",
    title: "Trusted Advisors",
    desc: "The Estatein team guided us through the entire buying process. Their knowledge and commitment to our needs were impressive. Thank you for your support!",
    rating: [
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
    ],
    name: "John Mans",
    country: "USA, Nevada",
  },
  {
    id: 4,
    image: "/Assets/Images/Profile-img-1.png",
    title: "Exceptional Service!",
    desc: "Our experience with Estatein was outstanding. Their team's dedication and professionalism made finding our dream home a breeze. Highly recommended!",
    rating: [
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
    ],
    name: "Wade Warren",
    country: "USA, California",
  },
  {
    id: 5,
    image: "/Assets/Images/Profile-img- 2.png",
    title: "Efficient and Reliable",
    desc: "Estatein provided us with top-notch service. They helped us sell our property quickly and at a great price. We couldn't be happier with the results.",
    rating: [
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
    ],
    name: "Emelie Thomson",
    country: "USA, Florida",
  },
  {
    id: 6,
    image: "/Assets/Images/Profile-img-3.png",
    title: "Trusted Advisors",
    desc: "The Estatein team guided us through the entire buying process. Their knowledge and commitment to our needs were impressive. Thank you for your support!",
    rating: [
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
        { icon: "/Assets/Icons/Testimonal-single-star-rating.png" },
    ],
    name: "John Mans",
    country: "USA, Nevada",
  },
];
export default Testimonals;
