import { Urbanist } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const Urbanist_font = Urbanist({
  subsets: ['latin'],
  variable: "--font-Urbanist",
  weight: ["400","500","600","700"],
});
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Real Estate Business Website",
  description: "Generated by create next app",
  icons: {
    icon: "/app/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Urbanist_font.variable} antialiased`}
      >
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
